version: "3.9"  # Use the latest stable version (as of March 2024)

services:
  client:
    build:
      context: ./client/.
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - mynetwork

  nginx:
    build: ./nginx/.
    ports:
      - "80:80"
    networks:
      - mynetwork
    depends_on:
      - client

networks:
  mynetwork:
    driver: bridge